### ISSUE TITLE
GetContractAddressFromTransactionID returns different contract address in protomainnet and mainnet

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#2174]
Mainnet:
```
curl --request POST \
  --url https://api.zilliqa.com/ \
  --header 'Content-Type: application/json' \
  --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetContractAddressFromTransactionID",
    "params": ["08bc0d50fe5aedf0d6b8a172424857281404abf4eaff259b67252e2c091d27ec"]
}'
```
response:
```
{
	"id": "1",
	"jsonrpc": "2.0",
	"result": "40d2225d5a8c99fda217c95c09cd0d9ac11c3499"
}
```

ProtoMainnet:
```
curl --request POST \
  --url https://api.zq2-protomainnet.zilliqa.com/ \
  --header 'Content-Type: application/json' \
  --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetContractAddressFromTransactionID",
    "params": ["08bc0d50fe5aedf0d6b8a172424857281404abf4eaff259b67252e2c091d27ec"]
}'
```

response:

```
{
	"jsonrpc": "2.0",
	"id": "1",
	"result": "cecbcfdcf83aa8b02fbc6aa0fe29572ffdf3be61"
}
```

**Comment by chetan-zilliqa** [comment]
I identified an issue while using Devex, where it displays an unusual contract creation address. While I understand that we don’t rely on Devex for our purposes, it is a valuable tool for spotting anomalies in API responses.

Here’s an example:
[Devex Link](https://devex.zilliqa.com/address/zil1grfzyh263jvlmgshe9wqnngdntq3cdye5dw4t6?network=https://api.zq2-protomainnet.zilliqa.com)

The reason Devex shows undefined under "Contract Creation" is that it identifies a different address than what it expects, leading to the inconsistency.

**Comment by chetan-zilliqa** [comment]
cc @DrZoltanFazekas

**Comment by saeed-zil** [comment]
Thanks to @chetan-zilliqa, I deployed and tested my #2206 branch on GCP and it looks good:
```bash
saeed_zilliqa_com@zq2-converter ~/persistence> curl --request POST \
                                                     --url http://localhost:4201/ \
                                                     --header 'Content-Type: application/json' \
                                                     --data '{
                                                   "id": "1",
                                                   "jsonrpc": "2.0",
                                                   "method": "GetContractAddressFromTransactionID",
                                                   "params": ["08bc0d50fe5aedf0d6b8a172424857281404abf4eaff259b67252e2c091d27ec"]
                                               }'
{"jsonrpc":"2.0","id":"1","result":"40d2225d5a8c99fda217c95c09cd0d9ac11c3499"}⏎
```

**Comment by chetan-zilliqa** [comment]
Hi @saeed-zil , I still see this issue.

protomainnet:
```
curl --request POST \
  --url https://api.zilliqa.com/ \
  --header 'Content-Type: application/json' \
  --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetContractAddressFromTransactionID",
    "params": ["0xd4a053d596a9089655e3549446c655b60568b12d7daf41262f02d0a2cdf213d2"]
}'

{
	"id": "1",
	"jsonrpc": "2.0",
	"result": "a845c1034cd077bd8d32be0447239c7e4be6cb21"
}


```

mainnet : 
```
curl --request POST \
  --url https://api.zq2-protomainnet.zilliqa.com/ \
  --header 'Content-Type: application/json' \
  --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetContractAddressFromTransactionID",
    "params": ["0xd4a053d596a9089655e3549446c655b60568b12d7daf41262f02d0a2cdf213d2"]
}'

{
	"jsonrpc": "2.0",
	"id": "1",
	"result": "7e89ac706732ba0c213f11766fe26cd63fd366b3"
}

```

**Comment by chetan-zilliqa** [comment]
I have assigned the issue to myself to test, as the API nodes are not updated and are still running the old version. Once they are updated to `v0.6.2`, the issue should be resolved.

**Comment by chetan-zilliqa** [comment]
```
$ curl --request POST   --url https://api.zilliqa.com/   --header 'Content-Type: application/json'   --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetContractAddressFromTransactionID",
    "params": ["0xd4a053d596a9089655e3549446c655b60568b12d7daf41262f02d0a2cdf213d2"]
}'|jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   256  100    78  100   178    546   1246 --:--:-- --:--:-- --:--:--  1802
{
  "id": "1",
  "jsonrpc": "2.0",
  "result": "a845c1034cd077bd8d32be0447239c7e4be6cb21"
}

$ curl --request POST   --url https://api.zq2-protomainnet.zilliqa.com/   --header 'Content-Type: application/json'   --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetContractAddressFromTransactionID",
    "params": ["0xd4a053d596a9089655e3549446c655b60568b12d7daf41262f02d0a2cdf213d2"]
}'|jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   256  100    78  100   178   1055   2408 --:--:-- --:--:-- --:--:--  3506
{
  "jsonrpc": "2.0",
  "id": "1",
  "result": "a845c1034cd077bd8d32be0447239c7e4be6cb21"
}

```
